/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.3--fx0.8.0--20210325--fix_android11_crash"
#endif /* AVUTIL_FFVERSION_H */
